Add light dark themes
PaymentHighway/paymenthighway-android-sdk pull request #4
Opened 2018-10-09 10:05 UTC by stepiro

Added roboto font.
min api 16.

2018-10-09 12:05 UTC, Swie requested changes

2018-10-09 12:05 UTC, Swie commented on demo/README.md
> +Payment Highway provide a [development `sandbox`](https://dev.paymenthighway.io/#development-sandbox) and a `production` environments.
provides

2018-10-09 12:05 UTC, Swie commented on demo/README.md
> +The demo app run in the `Sandbox` environment therefore uses the provided [sandbox `merchant id` and `account id`](https://dev.paymenthighway.io/#development-sandbox).
run**s** in the `Sandbox` environment **and** therefore

2018-10-09 12:05 UTC, Swie commented on demo/README.md
> +There is a helper where you can listen passing a lambda:
I think this sentence is missing some words, what do you mean?

listen XXX by passing a lambda ?

2018-10-09 12:05 UTC, Swie commented on demo/README.md
> +You can provide images for card text inputs implementing in your Activity the EditTextImageProvider interface:
card text inputs by implementing the EditTextImageProvider interface in your Activity:

2018-10-09 12:05 UTC, Swie commented on demo/README.md
> +In the demo there is a definition of a dark theme as a example. You can try it just uncommenting the definition of the colors in the file color.xml. You need set the variable `val themeDark = true` i
- an example
- try it just by uncommenting
- you need to set the variable

2018-10-09 12:05 UTC, Swie commented on demo/src/main/java/io/paymenthighway/demo/AddCardActivity.kt
> +    private fun getDrawableId(type: EditTextType): Int = when (type) {
Was this related to some limitations? Feels a bit weird having to care about theme colors in the code.
Or is it necessary for dynamic theme changes perhaps?

2018-10-09 12:15 UTC, stepiro commented on demo/README.md
> +Payment Highway provide a [development `sandbox`](https://dev.paymenthighway.io/#development-sandbox) and a `production` environments.
fixed thanks

2018-10-09 12:16 UTC, stepiro commented on demo/README.md
> +The demo app run in the `Sandbox` environment therefore uses the provided [sandbox `merchant id` and `account id`](https://dev.paymenthighway.io/#development-sandbox).
fixed, thanks

2018-10-09 12:16 UTC, stepiro commented on demo/README.md
> +You can provide images for card text inputs implementing in your Activity the EditTextImageProvider interface:
fixed

2018-10-15 13:15 UTC, Swie approved these changes

2018-10-16 05:54 UTC, merged